### ISSUE TITLE
libpdfsdk_jni.so not found on Android 12

### ISSUE THREAD

**Issue by Drakot** [benjinus/android-support-pdfium#8]
Installing an android 12 emulator version when opening a pdf it crashes with this exception.

```
 Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libpdfsdk_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at org.benjinus.pdfium.PdfiumSDK.<clinit>(PdfiumSDK.java:37)
        at com.test.app.utils.signature.pdfView.PDFView.<init>(PDFView.java:314)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
```

**Comment by georkost4** [comment]
Is there a known workaround to this?
